joiner:
  sleep: 0
  invite: "XmKtybzg"

raider:
  massping: false
  message: "# BEST DISCORD TOOLS\ndiscord.gg/v8mtTnJzsC\n stfu wither u lil yapper| "
  channelID: "1157899872419201044"
  guildID: "1153194049931595776"